version: "3"
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8000", "--no-browser", "--allow-root"]